apiVersion: v1
kind: Service
metadata:
  name: raft-service
  labels:
    app: rep
spec:
  clusterIP: None
  selector: # tiene que coincidir con label definido en pod de StatefulSet
    app: rep # Para dar de alta automaticamente en DNS a los PODS ligados
  ports:
  - port: 6000
    name: servidor-port
    protocol: TCP
    targetPort: 6000

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: raft
spec:
  serviceName: raft-service
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: rep
  template:
    metadata:
      labels:
        app: rep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: servidor
        image: localhost:5001/servidor:latest
        env:
        - name: MISUBDOMINIODNS
          value: raftGA-service.default.svc.cluster.local
        - name: MINOMBREPOD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /servidor/srvraft 
        - $(MINOMBREPOD)
        ports:
        - containerPort: 6000


#---

#apiVersion: v1
#kind: Pod
#metadata:
#  name: cliente
#spec:
#  restartPolicy: Never
#  containers:
#  - name: cliente
#    image: localhost:5001/cliente:latest
#    command:
#      - cltraft
#    ports:
#    - containerPort: 7000